### ISSUE TITLE
[homebridge-hubitat-makerapi] This plugin threw an error

### ISSUE THREAD

**Issue by cgmckeever** [danTapps/homebridge-hubitat-makerapi#23]
Im still trying to parse this to determine what device/action this might be attributed to. Will update if I find/resolve/get-more-info

[From HomeBridge](https://github.com/homebridge/homebridge/wiki/Characteristic-Warnings#this-plugin-threw-an-error-from-the-characteristic)
```
This plugin threw an error from the characteristic...
If you see this message in the log, the plugin threw an unhandled exception while processing the SET or GET request for the characteristic.
```

```
[homebridge-hubitat-makerapi] This plugin threw an error from the characteristic 'Brightness': Unhandled error thrown inside read handler for characteristic: Characteristic is not defined. See https://git.io/JtMGR for more info.
[12/29/2021, 8:38:40 AM] [homebridge-hubitat-makerapi] ReferenceError: Characteristic is not defined
    at validateValue (/homebridge/node_modules/homebridge-hubitat-makerapi/lib/validate.js:178:35)
    at Brightness.<anonymous> (/homebridge/node_modules/homebridge-hubitat-makerapi/accessories/he_st_accessories.js:650:40)
    at Brightness.emit (node:events:390:28)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1544:14
    at new Promise (<anonymous>)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1542:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Brightness.Characteristic.handleGetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:656:38)
    at Brightness.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1252:10)
    at HE_ST_Accessory.loadData (/homebridge/node_modules/homebridge-hubitat-makerapi/accessories/he_st_accessories.js:1614:63)
    at /homebridge/node_modules/homebridge-hubitat-makerapi/index.js:218:47
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by cgmckeever** [comment]
I _think_ this is attributed to trying to set/get the level of a lighting device that is not online (ie the main switch is off). Yes, I know, we leave smart lights powered .... Lots of switches, no great solutions. 

I've removed the 3 possible lights from MakerAPI and will continue to watch logs to see if this persists

**Comment by cgmckeever** [comment]
In the event its relevant, what was shared were the HE Groups and the HUE Groups of lighting that were offline. I have not tried if the actual device(s) were shared if MakerAPI tossed the same issue
